apiVersion: v1
kind: ServiceAccount
metadata:
  name: youtube-clone-ci
  namespace: dev
  labels:
    app.kubernetes.io/name: youtube-clone
    app.kubernetes.io/component: ci
automountServiceAccountToken: true
