global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: netflix-clone
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - netflix-clone
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: netflix-clone
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: replace
        target_label: __scrape__
        regex: "true"
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
